name: XCS234_Default
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8.10
  - notebook=6.5.4
  - tk=8.6.12
  - pandas=1.5.3
  - tensorboard=2.10.0
  - pyyaml=6.0
  - pip=23.0.1
  - pip:
    - matplotlib==3.7.1
    - numpy==1.24.3
    - gym==0.26.2
    - pygame==2.3.0
